version: 2
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.8"
  jobs:
    pre_install:
      - python -m pip install git+https://github.com/jianboqi/CSF.git
      - python -m pip install -r requirements.txt
      - python -c "from samgeo import SamGeo; from samgeo.text_sam import LangSAM;"

sphinx:
  configuration: docs/source/conf.py
